// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIBeOorGcmbTcPS3w_ADRIz_FhjGFoWwI',
    appId: '1:570648531036:web:085d1ec70ba6b14a0d9699',
    messagingSenderId: '570648531036',
    projectId: 'foodary-mobile-app',
    authDomain: 'foodary-mobile-app.firebaseapp.com',
    storageBucket: 'foodary-mobile-app.appspot.com',
    measurementId: 'G-CPJCDQ9DSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC4qJlI013PJTxZLYl7balM7i6n8M7UzI',
    appId: '1:570648531036:android:d3ef68696d25241e0d9699',
    messagingSenderId: '570648531036',
    projectId: 'foodary-mobile-app',
    storageBucket: 'foodary-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ViPgk_ULOXnhbZF4laEBPbxEZwbp2oM',
    appId: '1:570648531036:ios:6b292079d7b464d20d9699',
    messagingSenderId: '570648531036',
    projectId: 'foodary-mobile-app',
    storageBucket: 'foodary-mobile-app.appspot.com',
    androidClientId: '570648531036-pqqr9oeteq1qa3dklo2qmr8l1ots6nhg.apps.googleusercontent.com',
    iosClientId: '570648531036-ofte9r9gb5feei4u1o3jblm2676fiv96.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ViPgk_ULOXnhbZF4laEBPbxEZwbp2oM',
    appId: '1:570648531036:ios:6b292079d7b464d20d9699',
    messagingSenderId: '570648531036',
    projectId: 'foodary-mobile-app',
    storageBucket: 'foodary-mobile-app.appspot.com',
    androidClientId: '570648531036-pqqr9oeteq1qa3dklo2qmr8l1ots6nhg.apps.googleusercontent.com',
    iosClientId: '570648531036-ofte9r9gb5feei4u1o3jblm2676fiv96.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIBeOorGcmbTcPS3w_ADRIz_FhjGFoWwI',
    appId: '1:570648531036:web:c519ea50da0d897c0d9699',
    messagingSenderId: '570648531036',
    projectId: 'foodary-mobile-app',
    authDomain: 'foodary-mobile-app.firebaseapp.com',
    storageBucket: 'foodary-mobile-app.appspot.com',
    measurementId: 'G-XXLHTTW80P',
  );

}